#!/bin/bash
#Bash script that will display information about subdomains
if [ "$#" == 1 ];
then
    echo -n "The subdomain www is a "
    dig www."$1" | grep -A1 'ANSWER SECTION:' | awk '{printf $4}'
    printf " record and points to "
    dig www."$1" | grep -A1 'ANSWER SECTION:' | awk '{printf $5}'
    printf "\nThe subdomain lb-01 is a "
    dig lb-01."$1" | grep -A1 'ANSWER SECTION:' | awk '{printf $4}'
    printf " record and points to "
    dig lb-01."$1" | grep -A1 'ANSWER SECTION:' | awk '{printf $5}'
    printf "\nThe subdomain web-01 is a "
    dig web-01."$1" | grep -A1 'ANSWER SECTION:' | awk '{printf $4}'
    printf " record and points to "
    dig web-01."$1" | grep -A1 'ANSWER SECTION:' | awk '{printf $5}'
    printf "\nThe subdomain web-02 is a "
    dig web-02."$1" | grep -A1 'ANSWER SECTION:' | awk '{printf $4}'
    printf " record and points to "
    dig web-02."$1" | grep -A1 'ANSWER SECTION:' | awk '{printf $5}'
    printf "\n"
elif [ "$#" == 2 ];
then
    printf "The subdomain $2 is a "
    dig "$2.$1" | grep -A1 'ANSWER SECTION:' | awk '{printf $4}'
    printf " record and points to "
    dig "$2.$1" | grep -A1 'ANSWER SECTION:' | awk '{printf $5}'
    printf "\n"
fi
