#!/usr/bin/env bash
# configure server
apt-get update -y
apt install ufw -y
mkdir -p /var/www//html
ufw allow 'Nginx HTTP'
apt-get install nginx -y
echo "Holberton School" > /var/www/html/index.html
sed -i "/listen 80 default_server/a rewrite ^/redirect_me http://www.newdomain.com/newlocation permanent;" /etc/nginx/sites-available/default
service nginx restart
