#!/usr/bin/env bash
#Configure Nginx so that its HTTP response contains a custom header
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Holberton School" >> /var/www/html/index.html
echo "server {add_header X-Served-By $HOST}" >> /etc/nginx/sites-available/default
service nginx restart
