#!/usr/bin/env bash
#Configure Nginx so that its HTTP response contains a custom header
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Holberton School" > /var/www/html/index.html
mkdir -p /etc/nginx/sites-available/
touch /etc/nginx/sites-available/server.headers
echo "server {add_header X-Served-By $HOST}" >> /etc/nginx/sites-available/server.headers
service nginx restart
