#!/usr/bin/env bash                                                                        
# print 10 times and print hi on 9th iteration
counter=1
while [ $counter -le 10 ]
do
    echo Holberton School
    if (( counter == 9))
    then
        echo Hi
    fi
    ((counter++))
done
