#!/usr/bin/env bash                                                                        
counter=1
while [ $counter -le 10 ]
do
    echo Holberton School
    if (( counter == 9))
    then
        echo hi
    fi
    ((counter++))
done
