#!/usr/bin/env bash                                                                        

counter=0
while [ $counter -le 19 ]
do
    case $counter in
	4)
	    echo "bad luck from China"
	    ;;
	9)
	    echo 'bad luck from Japan'
	    ;;
	17)
	    echo 'bad luck from Italy'
	    ;;
    esac
    ((counter++))
    echo $counter
done
