#!/usr/bin/env bash
# count hours and min in half day
counter=0
count=1
while [ $counter -le 12 ]
do
    count=1
    echo Hour: $counter
    ((counter++))
    while [ $count -le 59 ]
    do
	echo $count
	((count++))
    done
done
