#!/usr/bin/env bash

if [ -e holbertonschool ]
then
    echo holbertonschool file exists
else
    echo holbertonschool file does not exist
fi

if [ -e holbertonschool ]
then
    if [ -s holbertonschool ]
    then
	echo holbertonschool file is not empty
    else
	echo holbertonschool file is empty
  
    fi
fi
if [ -e holbertonschool ]
then
    if [ -f holbertonschool ]
    then
        echo holbertonschool is a regular file
    fi
fi
